triggers:
- description: null
  envs: []
  last_enabled_at: 2024-08-16 19:49:05.238453+00:00
  name: trigger_at_launch
  pipeline_uuid: openaq_data_etl
  schedule_interval: '@once'
  schedule_type: time
  settings:
    create_initial_pipeline_run: true
  sla: null
  start_time: 2024-08-01 00:00:00+00:00
  status: active
  token: d97fc73976c34c3d851195e3222fcec6
  variables:
    d_end: 30
    d_start: 1
    experiment_name: 'initial_training '
    m_end: 6
    m_start: 1
    y_end: 2024
    y_start: 2022
