services:
  mage:
    image: mlops_zoommcamp_homework_5_extra:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV:-development}
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
    depends_on:
      - mage_db
    networks:
      - app-network
  mlflow:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "${PWD}/mlflow:/home/mlflow/"
    networks:
      - app-network

  mage_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_admin_pwd
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./postgres_config/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
