name: Deploy MAGE to Amazon ECS

on: 
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
        mask-aws-account-id: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      uses: docker/build-push-action@v6
      with:
        context: ./07-project/airquality/mage/
        file: ./07-project/airquality/mage/mage.Dockerfile
        push: true
        tags: |
          ${{ env.ECR_REGISTRY }}/${{ secrets.MAGE_ECR_REPOSITORY }}:latest
        provenance: false

    - name: Update Amazon ECS service
      run: |
        aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.MAGE_ECS_SERVICE }} --task-definition ${{ secrets.MAGE_ECS_TASK_DEFINITION }} --force-new-deployment